version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: google-auth
    versions:
    - 1.24.0
    - 1.25.0
    - 1.26.0
    - 1.26.1
    - 1.27.0
    - 1.27.1
    - 1.28.0
    - 1.28.1
    - 1.29.0
  - dependency-name: astroid
    versions:
    - 2.4.2
    - "2.5"
    - 2.5.1
    - 2.5.2
    - 2.5.3
  - dependency-name: firebase-admin
    versions:
    - 4.5.1
    - 4.5.2
    - 4.5.3
  - dependency-name: lazy-object-proxy
    versions:
    - 1.5.2
